title: Green Fingers
description: >
  Welcome to our blog about our garden app. We're glad you're here and would love to hear your feedback on our recent project changes. You can find them in the “Recent Posts” section.
baseurl: "/gardeningApp"
url: "https://dhbw-malte.github.io"
theme: minima
plugins:
  - jekyll-feed