title: Green Fingers
description: A simple blog using Jekyll and GitHub Pages
baseurl: "" # Leave blank unless you have a custom domain
url: "https://dhbw-malte.github.io/gardeningApp/"
theme: minima # Default GitHub Pages theme
plugins:
  - jekyll-feed
