title: My Jekyll Blog
description: A simple blog using Jekyll and GitHub Pages
baseurl: "" # Leave blank unless you have a custom domain
url: "https://DHBW-Malte.github.io/gardeningApp"
theme: minima # Default GitHub Pages theme
plugins:
  - jekyll-feed
