# Basic Settings
title: Green Fingers - The all-in-one plant app
description: "Thank you for being here, and thank you for visiting our blog. We regularly publish updates on the development of our GreenFingers app. This app will help all plant lovers and those who want to become plant lovers to take care of their plants and enjoy their plants for a long time. <br/><br/>Below you will find our blog posts, just choose one and start reading. We also appreciate your feedback and thoughts. You can use our comments section at the end of each post. To leave a comment, simply sign in with your Github account and let us know your thoughts. We look forward to hearing from you."
baseurl: "/gardeningApp"
url: "https://dhbw-malte.github.io"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-livereload
  - jekyll-seo-tag

# Livereload
livereload:
  enable: true
  port: 35730

# Exclude from build
exclude:
  - .expo
  - databaseStructure
  - GreenFingers
  - testReactNative
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .git

# Include specific files
include:
  - README.md

# Default Metadata
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Sima, Casimir, Ruan & Malte"
      comments: true
