jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Install Node dependencies
        working-directory: green-fingers
        run: npm ci

      - name: Grant execute permission to gradlew
        run: chmod +x android/gradlew
        working-directory: green-fingers

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: green-fingers/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: green-fingers-apk
          path: green-fingers/android/app/build/outputs/apk/release/app-release.apk
